### ISSUE TITLE
Cmap already in memory issue

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#112]
If you rerun a script that loads a colormap, the script fails because the cmap already exists. This requires a kernel restart every iteration of working on a plot and is annoying.

@anissa111 is this what you meant by cmap being broken?

**Comment by anissa111** [comment]
@jukent yes. This started happening with one of the more recent matplotlib updates that we pinned to have geocat-examples continue to work. Theoretically, this would be best handled in the cmaps package, but they don't seem to have active development anymore.

**Comment by jukent** [comment]
https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#colors-and-colormaps -- why we're pinned at matplotlib 3.5? Figure out what needs to be done differently with cmaps now.

**Comment by kafitzgerald** [comment]
related: 
* https://github.com/hhuangwx/cmaps/issues/6
* https://github.com/hhuangwx/cmaps/pull/7
* https://github.com/hhuangwx/cmaps/pull/5

So in newer versions of matplotlib you can't register a colormap with `matplotlib.cm.register_cmap` if it already exists and the function is deprecated since v3.7 ([docs here](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.register_cmap)).  

This code (mostly) lives in the cmaps repo, which doesn't seem to have active maintenance (there is an open issue and open PRs to address it).  It could potentially be addressed on our end in the examples repo with some error checking so we're not trying to re-register the colormaps and referencing them in a different way, but this would be pretty ugly and confusing.

We also use the function our `truncate_colormap` utility function: https://github.com/NCAR/geocat-viz/blob/main/src/geocat/viz/util.py#L607.  It looks like this is what was addressed in the existing PR with a potential workaround.  We should probably just move away from the deprecated colormaps stuff though.

I'm hopeful we can update the `truncate_colormap` bit on our end using the newer colormaps functionality, but the errors from duplicate colormap registration coming from cmaps I'm a little less clear what to do about.  Have we thought about pulling the NCL colormaps into this repo?  Not sure how many non-NCL colormaps we use from cmaps and/or if there might be issues with those, but I imagine the NCL ones we could get permission to integrate and/or use (if needed).  

I can start looking into the updates colormaps stuff from matplotlib and get an idea of how hard it might be to move away from the cmaps package if we're open to including the colormaps here (or somewhere else we could reference).

**Comment by jukent** [comment]
I'm in favor of moving NCL colormaps into this repo.

**Comment by kafitzgerald** [comment]
This should (hopefully) be [fixed](https://github.com/hhuangwx/cmaps/issues/8) now with PR #125 and version 2.0.1 of cmaps.  

While I think we might want to leave the umbrella issue open on viz, I'm hopeful we can close this.  Will do some testing as I clean up a couple of other colormaps related issues.

**Comment by kafitzgerald** [comment]
Sorry, I should have commented here again as I was digging through the CI failures over on examples.  While it's not as bad as before and I think we can address it on our end (i.e. in GeoCAT packages), I need to do a bit more work on `truncate_colormap` to fully address this for all versions of matplotlib.  

I'm going to reopen this for now, but will put in a PR (hopefully today) that addresses this.

**Comment by kafitzgerald** [comment]
Closing again since the CI failure was a false alarm (was using a much older version of viz).
