### ISSUE TITLE
documentation has error messages for seaborn import

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#262]
https://geocat-viz.readthedocs.io/en/latest/examples/plot_extrema_labels.html (seems to be for all examples)

`ImportError: The seaborn package is required  but could not be imported. Please install it with your package manager (e.g. conda or pip).`

**Comment by kafitzgerald** [comment]
This is the same thing from over on NCAR/geocat-examples#627 and #256 here I think, but I must have missed it since it wasn't failing in CI.

**Comment by kafitzgerald** [comment]
To fix this we could either skip the 2024.11.0 xarray version (this is what I did for geocat-examples), which I was trying to avoid here since this is a pretty narrow issue that only comes up w/ certain colormap specification, or we could rework the docs examples to avoid the issue (I did this with the viz test suite).

It seems like we could probably use some better checks as well to prevent this in the future.

**Comment by jukent** [comment]
Yes checks to actually let us know that the docs have errors.

I vote we skip the 2024.11.0 xarray version, as it will resolve itself in the next release (?) and we're at capacity / reworking the examples seems like extra work we don't need to do right now.

**Comment by kafitzgerald** [comment]
> Yes checks to actually let us know that the docs have errors.

I went ahead an logged a placeholder issue for this to separate it out.

> I vote we skip the 2024.11.0 xarray version, as it will resolve itself in the next release (?) and we're at capacity / reworking the examples seems like extra work we don't need to do right now.

Yeah, there's already a fix in over on xarray it just hasn't been released yet.  I'll go ahead and do this.
